services:
  db:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=maria
      - MYSQL_DATABASE=maria
      - MYSQL_USER=maria
      - MYSQL_PASSWORD=maria
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb:/var/lib/mysql

  wordpress:
    build: .
    image: wordpress:latest
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html/wp-content/plugins
    restart: always
